In [1]:
import torch

In [2]:
# requires_grad를 True로 설정하면 해당 텐서의 연산 내역을 추적함
# 이후 .backward()를 호출하여 모든 변화량을 계산할 수 있으며, 결과는 .grad에 누적됨
x = torch.ones(2, 2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [3]:
# detach()를 호출하여 해당 텐서의 연산 추적을 멈춤
xd = x.detach()
print(xd)
print(x)

tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [4]:
# torch.no_grad()를 사용하여 requires_grad=True인 텐서의 연산 추적을 멈춤
with torch.no_grad():
    # 텐서 연산.. (추적 X)
    pass

# 텐서 연산.. (추적 O)

In [5]:
# 모든 텐서는 Function과 연결되어있음
# (.grad_fn 속성에 연결되어있음)

# 사용자가 생성한 텐서의 .grad_fn은 기본값이 None이다.
# 텐서끼리 연산하여 나온 결과 텐서의 .grad_fn에는 해당 연산과 관련된 Function이 연결된다
print((x + 1).grad_fn)
print((xd + 1).grad_fn) # 연산을 추적하지 않기 때문에 기본값인 None

None


In [6]:
x = torch.ones(2, 2, requires_grad=True)
y = x + 2
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [7]:
t = torch.ones(2, 4)
t = t * 2 # 추적 X
t.requires_grad_(True) # 추적하도록 변경 (기존 텐서 덮어쓰기)
(t ** 2).grad_fn # 추적 O