In [1]:
import torch

In [5]:
# 초기화되지 않은 5*3 행렬 생성
x = torch.empty(5, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# 무작위 5*3 행렬 생성
x = torch.rand(5, 3)
x

tensor([[0.1612, 0.4650, 0.4938],
        [0.2663, 0.6351, 0.2662],
        [0.8076, 0.8863, 0.5262],
        [0.5522, 0.1197, 0.7876],
        [0.3768, 0.2402, 0.2317]])

In [8]:
# 타입이 long이고 0으로 채워진 5*3행렬 생성
x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [19]:
# 데이터로부터 직접 생성
x = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [21]:
# 기존의 x 행렬과 동일한 타입의 행렬 생성
# 값은 1로 초기화, 타입은 double
# 타입을 지정해주면 Override함
x = x.new_ones(5, 3, dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [24]:
# 랜덤값을 갖는 x와 동일한 Shape의 행렬 생성
# 타입은 float로 Override
x = torch.randn_like(x, dtype=torch.float)
x

tensor([[ 0.5180,  0.2155, -0.3785],
        [ 2.4454,  0.1081, -2.4083],
        [ 1.9627,  0.6587, -1.0842],
        [ 0.8997,  0.3820, -0.3474],
        [-0.2125,  1.3994, -1.6392]])

In [25]:
# 행렬의 크기, 튜플과 같음
x.size()

torch.Size([5, 3])