In [1]:
import torch

In [2]:
# 초기화되지 않은 5*3 행렬 생성
x = torch.empty(5, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [3]:
# 무작위 5*3 행렬 생성
x = torch.rand(5, 3)
x

tensor([[0.6409, 0.7247, 0.5453],
        [0.4236, 0.3816, 0.4026],
        [0.1458, 0.2084, 0.0676],
        [0.1379, 0.5249, 0.5102],
        [0.6372, 0.0995, 0.4275]])

In [4]:
# 타입이 long이고 0으로 채워진 5*3행렬 생성
x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [5]:
# 데이터로부터 직접 생성
x = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [6]:
# 기존의 x 행렬과 동일한 타입의 행렬 생성
# 값은 1로 초기화, 타입은 double
# 타입을 지정해주면 Override함
x = x.new_ones(5, 3, dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [7]:
# 랜덤값을 갖는 x와 동일한 Shape의 행렬 생성
# 타입은 float로 Override
x = torch.randn_like(x, dtype=torch.float)
x

tensor([[-0.9161,  1.3468, -0.0621],
        [ 0.7977, -0.7135, -0.5139],
        [-1.1993, -1.5992, -1.6528],
        [-1.4486, -1.5109, -0.5928],
        [ 1.4460,  0.3686, -1.0624]])

In [8]:
# 행렬의 크기, 튜플과 같음
x.size()

torch.Size([5, 3])